### ISSUE TITLE
Does not build with latest CFFI

### ISSUE THREAD

**Issue by quicklisp** [blindglobe/cl-blapack#2]
I get this error:

```
; caught ERROR:
;   (during macroexpansion of (DEFCFUN ("zdotc_" %ZDOTC) ...))
;   Unknown CFFI type: :COMPLEX-DOUBLE.
```

**Comment by blindglobe** [comment]
sionescu pointed out for fnv that cffi no longer accepts :type, just
type or 'type.

so I have a bit of editing to do.

thanks for the catch !

Sent from my iPod what's-a-ma-jiggy

Am 06.05.2012 um 18:24 schrieb Zach Beane
reply@reply.github.com:

**Comment by quicklisp** [comment]
I'm afraid the timing is somewhat poor - I hope to publish a Quicklisp update today. It looks like there may be a month without cl-blapack.

**Comment by blindglobe** [comment]
I might be able to update later this week, but unfortunately not
before Monday night euro-time at the earliest (Monday late afternoon
your time).

Sent from my iPod what's-a-ma-jiggy

Am 06.05.2012 um 19:02 schrieb Zach Beane
reply@reply.github.com:

**Comment by quicklisp** [comment]
Any word on this? I hope to make a release sometime very soon.

**Comment by idurand** [comment]
Hello,
I am trying to get the lisp-matrix system running but for this I need cl-blapack and I get the same problem as above
compiling the file 
blas-cffi.lisp

  error: 
    (during macroexpansion of (DEFCFUN ("zdotu_" %ZDOTU) ...))
    Unknown CFFI type: :COMPLEX-DOUBLE.

Is there any patch that I could use before this is fixed?
Irène

**Comment by Davidbhodge** [comment]
Hi. I would also be very interested in a patch.

**Comment by Davidbhodge** [comment]
Tony,

If you can point out what needs to be done, I'll do it.

This is not only for Cl-blapack, but also lisp-matrix as well I think.

Is it just mindlessly editing things or something more?

**Comment by blindglobe** [comment]
As far as I know, it's mindless editing -- basically need to unquote the C types.  But I've been floored at work (budget season and finances for my department) and at home (end of school year).   There is a suggested patch for FNV which basically shows what needs to be done for cl-blapack and lisp-matrix.

Apologies for the delays, but if you have a time, that would be great and appreciated...

best,
-tony

**Comment by blindglobe** [comment]
i.e. :complex-double should be complex-double  (no quote, no colon).... I think.

**Comment by Davidbhodge** [comment]
right. I tried complex-double, but looking at the CFFI mailing list actually showed its a little more complex. I think it needs to be fnv-fortran-complex-{double|float)  and the issue extends into lisp matrix.

And, if its any comfort, its end of quarter for me and the craziness is the same - so I completely understand.

Cheers

**Comment by Davidbhodge** [comment]
and just as an update, i have made the changes (and also nuked the included cffi, which was causing problems) and at least it now complies. I am now investigating how to run the tests

**Comment by Davidbhodge** [comment]
update#2: I run the unit test and get 7 failures and 20 errors, though its not clear how i figureo ut which test failed. Is that expected?

**Comment by sionescu** [comment]
Try the patch in pull request #3

**Comment by blindglobe** [comment]
Thanks sionescu, looks closed.
