### ISSUE TITLE
SBCL version scheme update breaks bug check (I think)

### ISSUE THREAD

**Issue by quicklisp** [blindglobe/cl-blapack#4]
On SBCL 1.1.1, cl-blapack tries to set the cl-block-gensym-bug feature, even though based on the comments it is apparently not needed. I think the switch to 1.0.x style versions to 1.1.x style may have caused the problem, but I haven't looked in detail.

This change means that cl-blapack won't build for me on sbcl 1.1.0.48 for example.

**Comment by blindglobe** [comment]
We had a report on this just yesterday.  I will look into this as soon as I
build a 1.1.x SBCL ! (ASAP, not like last time)

Sent from my iPod what's-a-ma-jiggy

Am 05.11.2012 um 18:18 schrieb Zach Beane notifications@github.com:

On SBCL 1.1.1, cl-blapack tries to set the cl-block-gensym-bug feature,
even though based on the comments it is apparently not needed. I think the
switch to 1.0.x style versions to 1.1.x style may have caused the problem,
but I haven't looked in detail.

This change means that cl-blapack won't build for me on sbcl 1.1.0.48 for
example.

—
Reply to this email directly or view it on
GitHubhttps://github.com/blindglobe/cl-blapack/issues/4.

**Comment by blindglobe** [comment]
I removed it, and it still seems to build (and work) for me.    Could someone else confirm that it builds?

**Comment by blindglobe** [comment]
Seems fine, now.  Report if not.
